version: '3.2'

services:
  bml_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements: requirements.txt
    container_name: bml
    restart: always
    volumes:
      - .:/bml
    command: make dev
    depends_on:
      - redis-bml
    ports:
      - 7999:7999
    networks:
      - bml_sawtooth_bml

  celery_worker:
    build:
      context: .
      dockerfile: api/worker/Dockerfile
    container_name: celery_worker
    restart: always
    volumes:
      - .:/bml
    command: make worker
    depends_on:
      - redis-bml
    networks:
      - bml_sawtooth_bml

  redis-bml:
    image: 'bitnami/redis:latest'
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_PASSWORD=redis
    logging:
      driver: none
    networks:
      - bml_sawtooth_bml


networks:
  bml_sawtooth_bml:
    external: true