# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/payload.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='protobuf/payload.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x16protobuf/payload.proto\"\x8e\x01\n\x13SimpleSupplyPayload\x12+\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1b.SimpleSupplyPayload.Action\x12*\n\x10synchronize_data\x18\x02 \x01(\x0b\x32\x10.SynchronizeData\"\x1e\n\x06\x41\x63tion\x12\x14\n\x10SYNCHRONIZE_DATA\x10\x00\"\x1f\n\x0fSynchronizeData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tb\x06proto3')
)

_SIMPLESUPPLYPAYLOAD_ACTION = _descriptor.EnumDescriptor(
    name='Action',
    full_name='SimpleSupplyPayload.Action',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='SYNCHRONIZE_DATA', index=0, number=0,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=139,
    serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_SIMPLESUPPLYPAYLOAD_ACTION)

_SIMPLESUPPLYPAYLOAD = _descriptor.Descriptor(
    name='SimpleSupplyPayload',
    full_name='SimpleSupplyPayload',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='action', full_name='SimpleSupplyPayload.action', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='synchronize_data', full_name='SimpleSupplyPayload.synchronize_data', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _SIMPLESUPPLYPAYLOAD_ACTION,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=27,
    serialized_end=169,
)

_SYNCHRONIZEDATA = _descriptor.Descriptor(
    name='SynchronizeData',
    full_name='SynchronizeData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='data', full_name='SynchronizeData.data', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=171,
    serialized_end=202,
)

_SIMPLESUPPLYPAYLOAD.fields_by_name['action'].enum_type = _SIMPLESUPPLYPAYLOAD_ACTION
_SIMPLESUPPLYPAYLOAD.fields_by_name['synchronize_data'].message_type = _SYNCHRONIZEDATA
_SIMPLESUPPLYPAYLOAD_ACTION.containing_type = _SIMPLESUPPLYPAYLOAD
DESCRIPTOR.message_types_by_name['SimpleSupplyPayload'] = _SIMPLESUPPLYPAYLOAD
DESCRIPTOR.message_types_by_name['SynchronizeData'] = _SYNCHRONIZEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleSupplyPayload = _reflection.GeneratedProtocolMessageType('SimpleSupplyPayload', (_message.Message,), {
    'DESCRIPTOR': _SIMPLESUPPLYPAYLOAD,
    '__module__': 'protobuf.payload_pb2'
    # @@protoc_insertion_point(class_scope:SimpleSupplyPayload)
})
_sym_db.RegisterMessage(SimpleSupplyPayload)

SynchronizeData = _reflection.GeneratedProtocolMessageType('SynchronizeData', (_message.Message,), {
    'DESCRIPTOR': _SYNCHRONIZEDATA,
    '__module__': 'protobuf.payload_pb2'
    # @@protoc_insertion_point(class_scope:SynchronizeData)
})
_sym_db.RegisterMessage(SynchronizeData)

# @@protoc_insertion_point(module_scope)
