# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/user.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='protobuf/user.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x13protobuf/user.proto\",\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\t\"\'\n\rUserContainer\x12\x16\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x05.Userb\x06proto3')
)

_USER = _descriptor.Descriptor(
    name='User',
    full_name='User',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='username', full_name='User.username', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='public_key', full_name='User.public_key', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=23,
    serialized_end=67,
)

_USERCONTAINER = _descriptor.Descriptor(
    name='UserContainer',
    full_name='UserContainer',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='entries', full_name='UserContainer.entries', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=69,
    serialized_end=108,
)

_USERCONTAINER.fields_by_name['entries'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserContainer'] = _USERCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
    'DESCRIPTOR': _USER,
    '__module__': 'protobuf.user_pb2'
    # @@protoc_insertion_point(class_scope:User)
})
_sym_db.RegisterMessage(User)

UserContainer = _reflection.GeneratedProtocolMessageType('UserContainer', (_message.Message,), {
    'DESCRIPTOR': _USERCONTAINER,
    '__module__': 'protobuf.user_pb2'
    # @@protoc_insertion_point(class_scope:UserContainer)
})
_sym_db.RegisterMessage(UserContainer)

# @@protoc_insertion_point(module_scope)
